# h/t to PK

version: "3.5"

services:
  # radarr:
  #   image: lscr.io/linuxserver/radarr:latest
  #   container_name: radarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los Angeles
  #   volumes:
  #     - /Users/aspanu/Media:/Media
  #   ports:
  #     - 7878:7878
  #   restart: unless-stopped

  # sonarr:
  #   image: lscr.io/linuxserver/sonarr:latest
  #   container_name: sonarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los Angeles
  #   volumes:
  #     - /Users/aspanu/Media:/Media
  #   ports:
  #     - 8989:8989
  #   restart: unless-stopped

  # bazarr:
  #   image: lscr.io/linuxserver/bazarr:latest
  #   container_name: bazarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los Angeles
  #   volumes:
  #     - /Users/aspanu/Media:/Media
  #   ports:
  #     - 6767:6767
  #   restart: unless-stopped

  # prowlarr:
  #   image: lscr.io/linuxserver/prowlarr:develop
  #   container_name: prowlarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los Angeles
  #   volumes:
  #     - /Users/aspanu/Media:/Media
  #   ports:
  #     - 9696:9696
  #   restart: unless-stopped

  # tautulli:
  #   image: lscr.io/linuxserver/tautulli:latest
  #   container_name: tautulli
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los Angeles
  #   volumes:
  #     - /Users/aspanu/Media:/Media
  #   ports:
  #     - 8181:8181
  #   restart: unless-stopped

  # overseerr:
  #   image: lscr.io/linuxserver/overseerr:latest
  #   container_name: overseerr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los Angeles
  #   volumes:
  #     - /Users/aspanu/Media:/Media
  #   ports:
  #     - 5055:5055
  #   restart: unless-stopped

  # qbittorrent:
  #   image: lscr.io/linuxserver/qbittorrent:latest
  #   container_name: qbittorrent
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Los Angeles
  #     - WEBUI_PORT=6969
  #   volumes:
  #     - /Users/aspanu/Media:/Media
  #   ports:
  #     - 6969:6969
  #     - 6881:6881
  #     - 6881:6881/udp
  #   restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /Users/aspanu/Media:/Media
    # ports:
    #   - 32400:32400
    restart: unless-stopped
